### ISSUE TITLE
[ProjectWindow] Content position

### ISSUE THREAD

**Issue by MLGMAG** [Tim2313/Tim2313.github.io#1]
Center the content of the page.

**Comment by MLGMAG** [comment]
![image](https://github.com/Tim2313/Tim2313.github.io/assets/27917560/c64bfec4-2c82-464d-8d2b-1b1f57dc14df)

**Comment by Tim2313** [comment]
fix issue 4eba97d1ea35aa85d33c15ad66bfcdd33df36e36
